name: UI-Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # 1 checkout the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folder
        run: ls
    # Install the dependencies
    # run tests
