name: UI-Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # 1 checkout the code
        uses: actions/checkout@v4
      - name: Setup Node  # Install the dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test     # run tests
